# Generated by Django 3.1 on 2021-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210119_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('date_joined', models.DateField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('whatsapp', models.IntegerField()),
            ],
        ),
    ]
