# Generated by Django 3.1 on 2021-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210119_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='member_profile_pics'),
        ),
    ]
